/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RateLimitsRouteImport } from './routes/rate-limits'
import { Route as ProfileAnalyzeRouteImport } from './routes/profile-analyze'
import { Route as NetworkMapRouteImport } from './routes/network-map'
import { Route as MentionsRouteImport } from './routes/mentions'
import { Route as LinksRouteImport } from './routes/links'
import { Route as LikesRouteImport } from './routes/likes'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DmsRouteImport } from './routes/dms'
import { Route as DiscussRouteImport } from './routes/discuss'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilesHandleRouteImport } from './routes/profiles.$handle'
import { Route as AuthorsHandleRouteImport } from './routes/authors.$handle'
import { Route as ApiXurlRateLimitsRouteImport } from './routes/api/xurl-rate-limits'
import { Route as ApiXremarkRouteImport } from './routes/api/xremark'
import { Route as ApiWeeklyDigestHistoryRouteImport } from './routes/api/weekly-digest-history'
import { Route as ApiTwillotHistoryRouteImport } from './routes/api/twillot-history'
import { Route as ApiTweetVideoRouteImport } from './routes/api/tweet-video'
import { Route as ApiTweetTranslationRouteImport } from './routes/api/tweet-translation'
import { Route as ApiTweetScoresRouteImport } from './routes/api/tweet-scores'
import { Route as ApiTweetExpandRouteImport } from './routes/api/tweet-expand'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiSpecialFollowPositionRouteImport } from './routes/api/special-follow-position'
import { Route as ApiSpecialFollowFeedRouteImport } from './routes/api/special-follow-feed'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiSearchDiscussionRouteImport } from './routes/api/search-discussion'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as ApiProfilePriorityRouteImport } from './routes/api/profile-priority'
import { Route as ApiProfileHydrateRouteImport } from './routes/api/profile-hydrate'
import { Route as ApiProfileAnalysisRouteImport } from './routes/api/profile-analysis'
import { Route as ApiPeriodDigestHistoryRouteImport } from './routes/api/period-digest-history'
import { Route as ApiPeriodDigestRouteImport } from './routes/api/period-digest'
import { Route as ApiNetworkMapRouteImport } from './routes/api/network-map'
import { Route as ApiLinkPreviewRouteImport } from './routes/api/link-preview'
import { Route as ApiLinkInsightsRouteImport } from './routes/api/link-insights'
import { Route as ApiInboxRouteImport } from './routes/api/inbox'
import { Route as ApiFeedSyncRouteImport } from './routes/api/feed-sync'
import { Route as ApiFeedArticleRouteImport } from './routes/api/feed-article'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiDiscussionHistoryRouteImport } from './routes/api/discussion-history'
import { Route as ApiDataSourcesRouteImport } from './routes/api/data-sources'
import { Route as ApiConversationRouteImport } from './routes/api/conversation'
import { Route as ApiBookmarkRouteImport } from './routes/api/bookmark'
import { Route as ApiBlocksRouteImport } from './routes/api/blocks'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as ApiActionRouteImport } from './routes/api/action'
import { Route as ApiIntegrationsXremarkRouteImport } from './routes/api/integrations.xremark'
import { Route as ApiIntegrationsTwitter6551RouteImport } from './routes/api/integrations.twitter6551'
import { Route as ApiIntegrationsTwillotHistoryRouteImport } from './routes/api/integrations.twillot-history'
import { Route as ApiIntegrationsXremarkSnapshotRouteImport } from './routes/api/integrations.xremark.snapshot'
import { Route as ApiIntegrationsXremarkChangesRouteImport } from './routes/api/integrations.xremark.changes'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RateLimitsRoute = RateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAnalyzeRoute = ProfileAnalyzeRouteImport.update({
  id: '/profile-analyze',
  path: '/profile-analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkMapRoute = NetworkMapRouteImport.update({
  id: '/network-map',
  path: '/network-map',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsRoute = MentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const LikesRoute = LikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DmsRoute = DmsRouteImport.update({
  id: '/dms',
  path: '/dms',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussRoute = DiscussRouteImport.update({
  id: '/discuss',
  path: '/discuss',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesHandleRoute = ProfilesHandleRouteImport.update({
  id: '/profiles/$handle',
  path: '/profiles/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsHandleRoute = AuthorsHandleRouteImport.update({
  id: '/authors/$handle',
  path: '/authors/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXurlRateLimitsRoute = ApiXurlRateLimitsRouteImport.update({
  id: '/api/xurl-rate-limits',
  path: '/api/xurl-rate-limits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXremarkRoute = ApiXremarkRouteImport.update({
  id: '/api/xremark',
  path: '/api/xremark',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeeklyDigestHistoryRoute = ApiWeeklyDigestHistoryRouteImport.update({
  id: '/api/weekly-digest-history',
  path: '/api/weekly-digest-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwillotHistoryRoute = ApiTwillotHistoryRouteImport.update({
  id: '/api/twillot-history',
  path: '/api/twillot-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTweetVideoRoute = ApiTweetVideoRouteImport.update({
  id: '/api/tweet-video',
  path: '/api/tweet-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTweetTranslationRoute = ApiTweetTranslationRouteImport.update({
  id: '/api/tweet-translation',
  path: '/api/tweet-translation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTweetScoresRoute = ApiTweetScoresRouteImport.update({
  id: '/api/tweet-scores',
  path: '/api/tweet-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTweetExpandRoute = ApiTweetExpandRouteImport.update({
  id: '/api/tweet-expand',
  path: '/api/tweet-expand',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpecialFollowPositionRoute =
  ApiSpecialFollowPositionRouteImport.update({
    id: '/api/special-follow-position',
    path: '/api/special-follow-position',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSpecialFollowFeedRoute = ApiSpecialFollowFeedRouteImport.update({
  id: '/api/special-follow-feed',
  path: '/api/special-follow-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchDiscussionRoute = ApiSearchDiscussionRouteImport.update({
  id: '/api/search-discussion',
  path: '/api/search-discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilePriorityRoute = ApiProfilePriorityRouteImport.update({
  id: '/api/profile-priority',
  path: '/api/profile-priority',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileHydrateRoute = ApiProfileHydrateRouteImport.update({
  id: '/api/profile-hydrate',
  path: '/api/profile-hydrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileAnalysisRoute = ApiProfileAnalysisRouteImport.update({
  id: '/api/profile-analysis',
  path: '/api/profile-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeriodDigestHistoryRoute = ApiPeriodDigestHistoryRouteImport.update({
  id: '/api/period-digest-history',
  path: '/api/period-digest-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeriodDigestRoute = ApiPeriodDigestRouteImport.update({
  id: '/api/period-digest',
  path: '/api/period-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetworkMapRoute = ApiNetworkMapRouteImport.update({
  id: '/api/network-map',
  path: '/api/network-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkPreviewRoute = ApiLinkPreviewRouteImport.update({
  id: '/api/link-preview',
  path: '/api/link-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkInsightsRoute = ApiLinkInsightsRouteImport.update({
  id: '/api/link-insights',
  path: '/api/link-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedSyncRoute = ApiFeedSyncRouteImport.update({
  id: '/api/feed-sync',
  path: '/api/feed-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedArticleRoute = ApiFeedArticleRouteImport.update({
  id: '/api/feed-article',
  path: '/api/feed-article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscussionHistoryRoute = ApiDiscussionHistoryRouteImport.update({
  id: '/api/discussion-history',
  path: '/api/discussion-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataSourcesRoute = ApiDataSourcesRouteImport.update({
  id: '/api/data-sources',
  path: '/api/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationRoute = ApiConversationRouteImport.update({
  id: '/api/conversation',
  path: '/api/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarkRoute = ApiBookmarkRouteImport.update({
  id: '/api/bookmark',
  path: '/api/bookmark',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlocksRoute = ApiBlocksRouteImport.update({
  id: '/api/blocks',
  path: '/api/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionRoute = ApiActionRouteImport.update({
  id: '/api/action',
  path: '/api/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsXremarkRoute = ApiIntegrationsXremarkRouteImport.update({
  id: '/api/integrations/xremark',
  path: '/api/integrations/xremark',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsTwitter6551Route =
  ApiIntegrationsTwitter6551RouteImport.update({
    id: '/api/integrations/twitter6551',
    path: '/api/integrations/twitter6551',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsTwillotHistoryRoute =
  ApiIntegrationsTwillotHistoryRouteImport.update({
    id: '/api/integrations/twillot-history',
    path: '/api/integrations/twillot-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsXremarkSnapshotRoute =
  ApiIntegrationsXremarkSnapshotRouteImport.update({
    id: '/snapshot',
    path: '/snapshot',
    getParentRoute: () => ApiIntegrationsXremarkRoute,
  } as any)
const ApiIntegrationsXremarkChangesRoute =
  ApiIntegrationsXremarkChangesRouteImport.update({
    id: '/changes',
    path: '/changes',
    getParentRoute: () => ApiIntegrationsXremarkRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/bookmarks': typeof BookmarksRoute
  '/data-sources': typeof DataSourcesRoute
  '/discuss': typeof DiscussRoute
  '/dms': typeof DmsRoute
  '/feed': typeof FeedRoute
  '/inbox': typeof InboxRoute
  '/likes': typeof LikesRoute
  '/links': typeof LinksRoute
  '/mentions': typeof MentionsRoute
  '/network-map': typeof NetworkMapRoute
  '/profile-analyze': typeof ProfileAnalyzeRoute
  '/rate-limits': typeof RateLimitsRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/api/action': typeof ApiActionRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/bookmark': typeof ApiBookmarkRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/data-sources': typeof ApiDataSourcesRoute
  '/api/discussion-history': typeof ApiDiscussionHistoryRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/feed-article': typeof ApiFeedArticleRoute
  '/api/feed-sync': typeof ApiFeedSyncRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/link-insights': typeof ApiLinkInsightsRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/network-map': typeof ApiNetworkMapRoute
  '/api/period-digest': typeof ApiPeriodDigestRoute
  '/api/period-digest-history': typeof ApiPeriodDigestHistoryRoute
  '/api/profile-analysis': typeof ApiProfileAnalysisRoute
  '/api/profile-hydrate': typeof ApiProfileHydrateRoute
  '/api/profile-priority': typeof ApiProfilePriorityRoute
  '/api/query': typeof ApiQueryRoute
  '/api/search-discussion': typeof ApiSearchDiscussionRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/special-follow-feed': typeof ApiSpecialFollowFeedRoute
  '/api/special-follow-position': typeof ApiSpecialFollowPositionRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/tweet-expand': typeof ApiTweetExpandRoute
  '/api/tweet-scores': typeof ApiTweetScoresRoute
  '/api/tweet-translation': typeof ApiTweetTranslationRoute
  '/api/tweet-video': typeof ApiTweetVideoRoute
  '/api/twillot-history': typeof ApiTwillotHistoryRoute
  '/api/weekly-digest-history': typeof ApiWeeklyDigestHistoryRoute
  '/api/xremark': typeof ApiXremarkRoute
  '/api/xurl-rate-limits': typeof ApiXurlRateLimitsRoute
  '/authors/$handle': typeof AuthorsHandleRoute
  '/profiles/$handle': typeof ProfilesHandleRoute
  '/api/integrations/twillot-history': typeof ApiIntegrationsTwillotHistoryRoute
  '/api/integrations/twitter6551': typeof ApiIntegrationsTwitter6551Route
  '/api/integrations/xremark': typeof ApiIntegrationsXremarkRouteWithChildren
  '/api/integrations/xremark/changes': typeof ApiIntegrationsXremarkChangesRoute
  '/api/integrations/xremark/snapshot': typeof ApiIntegrationsXremarkSnapshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/bookmarks': typeof BookmarksRoute
  '/data-sources': typeof DataSourcesRoute
  '/discuss': typeof DiscussRoute
  '/dms': typeof DmsRoute
  '/feed': typeof FeedRoute
  '/inbox': typeof InboxRoute
  '/likes': typeof LikesRoute
  '/links': typeof LinksRoute
  '/mentions': typeof MentionsRoute
  '/network-map': typeof NetworkMapRoute
  '/profile-analyze': typeof ProfileAnalyzeRoute
  '/rate-limits': typeof RateLimitsRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/api/action': typeof ApiActionRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/bookmark': typeof ApiBookmarkRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/data-sources': typeof ApiDataSourcesRoute
  '/api/discussion-history': typeof ApiDiscussionHistoryRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/feed-article': typeof ApiFeedArticleRoute
  '/api/feed-sync': typeof ApiFeedSyncRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/link-insights': typeof ApiLinkInsightsRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/network-map': typeof ApiNetworkMapRoute
  '/api/period-digest': typeof ApiPeriodDigestRoute
  '/api/period-digest-history': typeof ApiPeriodDigestHistoryRoute
  '/api/profile-analysis': typeof ApiProfileAnalysisRoute
  '/api/profile-hydrate': typeof ApiProfileHydrateRoute
  '/api/profile-priority': typeof ApiProfilePriorityRoute
  '/api/query': typeof ApiQueryRoute
  '/api/search-discussion': typeof ApiSearchDiscussionRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/special-follow-feed': typeof ApiSpecialFollowFeedRoute
  '/api/special-follow-position': typeof ApiSpecialFollowPositionRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/tweet-expand': typeof ApiTweetExpandRoute
  '/api/tweet-scores': typeof ApiTweetScoresRoute
  '/api/tweet-translation': typeof ApiTweetTranslationRoute
  '/api/tweet-video': typeof ApiTweetVideoRoute
  '/api/twillot-history': typeof ApiTwillotHistoryRoute
  '/api/weekly-digest-history': typeof ApiWeeklyDigestHistoryRoute
  '/api/xremark': typeof ApiXremarkRoute
  '/api/xurl-rate-limits': typeof ApiXurlRateLimitsRoute
  '/authors/$handle': typeof AuthorsHandleRoute
  '/profiles/$handle': typeof ProfilesHandleRoute
  '/api/integrations/twillot-history': typeof ApiIntegrationsTwillotHistoryRoute
  '/api/integrations/twitter6551': typeof ApiIntegrationsTwitter6551Route
  '/api/integrations/xremark': typeof ApiIntegrationsXremarkRouteWithChildren
  '/api/integrations/xremark/changes': typeof ApiIntegrationsXremarkChangesRoute
  '/api/integrations/xremark/snapshot': typeof ApiIntegrationsXremarkSnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/bookmarks': typeof BookmarksRoute
  '/data-sources': typeof DataSourcesRoute
  '/discuss': typeof DiscussRoute
  '/dms': typeof DmsRoute
  '/feed': typeof FeedRoute
  '/inbox': typeof InboxRoute
  '/likes': typeof LikesRoute
  '/links': typeof LinksRoute
  '/mentions': typeof MentionsRoute
  '/network-map': typeof NetworkMapRoute
  '/profile-analyze': typeof ProfileAnalyzeRoute
  '/rate-limits': typeof RateLimitsRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/api/action': typeof ApiActionRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/bookmark': typeof ApiBookmarkRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/data-sources': typeof ApiDataSourcesRoute
  '/api/discussion-history': typeof ApiDiscussionHistoryRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/feed-article': typeof ApiFeedArticleRoute
  '/api/feed-sync': typeof ApiFeedSyncRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/link-insights': typeof ApiLinkInsightsRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/network-map': typeof ApiNetworkMapRoute
  '/api/period-digest': typeof ApiPeriodDigestRoute
  '/api/period-digest-history': typeof ApiPeriodDigestHistoryRoute
  '/api/profile-analysis': typeof ApiProfileAnalysisRoute
  '/api/profile-hydrate': typeof ApiProfileHydrateRoute
  '/api/profile-priority': typeof ApiProfilePriorityRoute
  '/api/query': typeof ApiQueryRoute
  '/api/search-discussion': typeof ApiSearchDiscussionRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/special-follow-feed': typeof ApiSpecialFollowFeedRoute
  '/api/special-follow-position': typeof ApiSpecialFollowPositionRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/tweet-expand': typeof ApiTweetExpandRoute
  '/api/tweet-scores': typeof ApiTweetScoresRoute
  '/api/tweet-translation': typeof ApiTweetTranslationRoute
  '/api/tweet-video': typeof ApiTweetVideoRoute
  '/api/twillot-history': typeof ApiTwillotHistoryRoute
  '/api/weekly-digest-history': typeof ApiWeeklyDigestHistoryRoute
  '/api/xremark': typeof ApiXremarkRoute
  '/api/xurl-rate-limits': typeof ApiXurlRateLimitsRoute
  '/authors/$handle': typeof AuthorsHandleRoute
  '/profiles/$handle': typeof ProfilesHandleRoute
  '/api/integrations/twillot-history': typeof ApiIntegrationsTwillotHistoryRoute
  '/api/integrations/twitter6551': typeof ApiIntegrationsTwitter6551Route
  '/api/integrations/xremark': typeof ApiIntegrationsXremarkRouteWithChildren
  '/api/integrations/xremark/changes': typeof ApiIntegrationsXremarkChangesRoute
  '/api/integrations/xremark/snapshot': typeof ApiIntegrationsXremarkSnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/bookmarks'
    | '/data-sources'
    | '/discuss'
    | '/dms'
    | '/feed'
    | '/inbox'
    | '/likes'
    | '/links'
    | '/mentions'
    | '/network-map'
    | '/profile-analyze'
    | '/rate-limits'
    | '/settings'
    | '/today'
    | '/api/action'
    | '/api/avatar'
    | '/api/blocks'
    | '/api/bookmark'
    | '/api/conversation'
    | '/api/data-sources'
    | '/api/discussion-history'
    | '/api/feed'
    | '/api/feed-article'
    | '/api/feed-sync'
    | '/api/inbox'
    | '/api/link-insights'
    | '/api/link-preview'
    | '/api/network-map'
    | '/api/period-digest'
    | '/api/period-digest-history'
    | '/api/profile-analysis'
    | '/api/profile-hydrate'
    | '/api/profile-priority'
    | '/api/query'
    | '/api/search-discussion'
    | '/api/settings'
    | '/api/special-follow-feed'
    | '/api/special-follow-position'
    | '/api/status'
    | '/api/sync'
    | '/api/tweet-expand'
    | '/api/tweet-scores'
    | '/api/tweet-translation'
    | '/api/tweet-video'
    | '/api/twillot-history'
    | '/api/weekly-digest-history'
    | '/api/xremark'
    | '/api/xurl-rate-limits'
    | '/authors/$handle'
    | '/profiles/$handle'
    | '/api/integrations/twillot-history'
    | '/api/integrations/twitter6551'
    | '/api/integrations/xremark'
    | '/api/integrations/xremark/changes'
    | '/api/integrations/xremark/snapshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks'
    | '/bookmarks'
    | '/data-sources'
    | '/discuss'
    | '/dms'
    | '/feed'
    | '/inbox'
    | '/likes'
    | '/links'
    | '/mentions'
    | '/network-map'
    | '/profile-analyze'
    | '/rate-limits'
    | '/settings'
    | '/today'
    | '/api/action'
    | '/api/avatar'
    | '/api/blocks'
    | '/api/bookmark'
    | '/api/conversation'
    | '/api/data-sources'
    | '/api/discussion-history'
    | '/api/feed'
    | '/api/feed-article'
    | '/api/feed-sync'
    | '/api/inbox'
    | '/api/link-insights'
    | '/api/link-preview'
    | '/api/network-map'
    | '/api/period-digest'
    | '/api/period-digest-history'
    | '/api/profile-analysis'
    | '/api/profile-hydrate'
    | '/api/profile-priority'
    | '/api/query'
    | '/api/search-discussion'
    | '/api/settings'
    | '/api/special-follow-feed'
    | '/api/special-follow-position'
    | '/api/status'
    | '/api/sync'
    | '/api/tweet-expand'
    | '/api/tweet-scores'
    | '/api/tweet-translation'
    | '/api/tweet-video'
    | '/api/twillot-history'
    | '/api/weekly-digest-history'
    | '/api/xremark'
    | '/api/xurl-rate-limits'
    | '/authors/$handle'
    | '/profiles/$handle'
    | '/api/integrations/twillot-history'
    | '/api/integrations/twitter6551'
    | '/api/integrations/xremark'
    | '/api/integrations/xremark/changes'
    | '/api/integrations/xremark/snapshot'
  id:
    | '__root__'
    | '/'
    | '/blocks'
    | '/bookmarks'
    | '/data-sources'
    | '/discuss'
    | '/dms'
    | '/feed'
    | '/inbox'
    | '/likes'
    | '/links'
    | '/mentions'
    | '/network-map'
    | '/profile-analyze'
    | '/rate-limits'
    | '/settings'
    | '/today'
    | '/api/action'
    | '/api/avatar'
    | '/api/blocks'
    | '/api/bookmark'
    | '/api/conversation'
    | '/api/data-sources'
    | '/api/discussion-history'
    | '/api/feed'
    | '/api/feed-article'
    | '/api/feed-sync'
    | '/api/inbox'
    | '/api/link-insights'
    | '/api/link-preview'
    | '/api/network-map'
    | '/api/period-digest'
    | '/api/period-digest-history'
    | '/api/profile-analysis'
    | '/api/profile-hydrate'
    | '/api/profile-priority'
    | '/api/query'
    | '/api/search-discussion'
    | '/api/settings'
    | '/api/special-follow-feed'
    | '/api/special-follow-position'
    | '/api/status'
    | '/api/sync'
    | '/api/tweet-expand'
    | '/api/tweet-scores'
    | '/api/tweet-translation'
    | '/api/tweet-video'
    | '/api/twillot-history'
    | '/api/weekly-digest-history'
    | '/api/xremark'
    | '/api/xurl-rate-limits'
    | '/authors/$handle'
    | '/profiles/$handle'
    | '/api/integrations/twillot-history'
    | '/api/integrations/twitter6551'
    | '/api/integrations/xremark'
    | '/api/integrations/xremark/changes'
    | '/api/integrations/xremark/snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksRoute: typeof BlocksRoute
  BookmarksRoute: typeof BookmarksRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DiscussRoute: typeof DiscussRoute
  DmsRoute: typeof DmsRoute
  FeedRoute: typeof FeedRoute
  InboxRoute: typeof InboxRoute
  LikesRoute: typeof LikesRoute
  LinksRoute: typeof LinksRoute
  MentionsRoute: typeof MentionsRoute
  NetworkMapRoute: typeof NetworkMapRoute
  ProfileAnalyzeRoute: typeof ProfileAnalyzeRoute
  RateLimitsRoute: typeof RateLimitsRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRoute
  ApiActionRoute: typeof ApiActionRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiBlocksRoute: typeof ApiBlocksRoute
  ApiBookmarkRoute: typeof ApiBookmarkRoute
  ApiConversationRoute: typeof ApiConversationRoute
  ApiDataSourcesRoute: typeof ApiDataSourcesRoute
  ApiDiscussionHistoryRoute: typeof ApiDiscussionHistoryRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiFeedArticleRoute: typeof ApiFeedArticleRoute
  ApiFeedSyncRoute: typeof ApiFeedSyncRoute
  ApiInboxRoute: typeof ApiInboxRoute
  ApiLinkInsightsRoute: typeof ApiLinkInsightsRoute
  ApiLinkPreviewRoute: typeof ApiLinkPreviewRoute
  ApiNetworkMapRoute: typeof ApiNetworkMapRoute
  ApiPeriodDigestRoute: typeof ApiPeriodDigestRoute
  ApiPeriodDigestHistoryRoute: typeof ApiPeriodDigestHistoryRoute
  ApiProfileAnalysisRoute: typeof ApiProfileAnalysisRoute
  ApiProfileHydrateRoute: typeof ApiProfileHydrateRoute
  ApiProfilePriorityRoute: typeof ApiProfilePriorityRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApiSearchDiscussionRoute: typeof ApiSearchDiscussionRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiSpecialFollowFeedRoute: typeof ApiSpecialFollowFeedRoute
  ApiSpecialFollowPositionRoute: typeof ApiSpecialFollowPositionRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiTweetExpandRoute: typeof ApiTweetExpandRoute
  ApiTweetScoresRoute: typeof ApiTweetScoresRoute
  ApiTweetTranslationRoute: typeof ApiTweetTranslationRoute
  ApiTweetVideoRoute: typeof ApiTweetVideoRoute
  ApiTwillotHistoryRoute: typeof ApiTwillotHistoryRoute
  ApiWeeklyDigestHistoryRoute: typeof ApiWeeklyDigestHistoryRoute
  ApiXremarkRoute: typeof ApiXremarkRoute
  ApiXurlRateLimitsRoute: typeof ApiXurlRateLimitsRoute
  AuthorsHandleRoute: typeof AuthorsHandleRoute
  ProfilesHandleRoute: typeof ProfilesHandleRoute
  ApiIntegrationsTwillotHistoryRoute: typeof ApiIntegrationsTwillotHistoryRoute
  ApiIntegrationsTwitter6551Route: typeof ApiIntegrationsTwitter6551Route
  ApiIntegrationsXremarkRoute: typeof ApiIntegrationsXremarkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-limits': {
      id: '/rate-limits'
      path: '/rate-limits'
      fullPath: '/rate-limits'
      preLoaderRoute: typeof RateLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-analyze': {
      id: '/profile-analyze'
      path: '/profile-analyze'
      fullPath: '/profile-analyze'
      preLoaderRoute: typeof ProfileAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-map': {
      id: '/network-map'
      path: '/network-map'
      fullPath: '/network-map'
      preLoaderRoute: typeof NetworkMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions': {
      id: '/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof MentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/likes': {
      id: '/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof LikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dms': {
      id: '/dms'
      path: '/dms'
      fullPath: '/dms'
      preLoaderRoute: typeof DmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discuss': {
      id: '/discuss'
      path: '/discuss'
      fullPath: '/discuss'
      preLoaderRoute: typeof DiscussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$handle': {
      id: '/profiles/$handle'
      path: '/profiles/$handle'
      fullPath: '/profiles/$handle'
      preLoaderRoute: typeof ProfilesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$handle': {
      id: '/authors/$handle'
      path: '/authors/$handle'
      fullPath: '/authors/$handle'
      preLoaderRoute: typeof AuthorsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xurl-rate-limits': {
      id: '/api/xurl-rate-limits'
      path: '/api/xurl-rate-limits'
      fullPath: '/api/xurl-rate-limits'
      preLoaderRoute: typeof ApiXurlRateLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xremark': {
      id: '/api/xremark'
      path: '/api/xremark'
      fullPath: '/api/xremark'
      preLoaderRoute: typeof ApiXremarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weekly-digest-history': {
      id: '/api/weekly-digest-history'
      path: '/api/weekly-digest-history'
      fullPath: '/api/weekly-digest-history'
      preLoaderRoute: typeof ApiWeeklyDigestHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twillot-history': {
      id: '/api/twillot-history'
      path: '/api/twillot-history'
      fullPath: '/api/twillot-history'
      preLoaderRoute: typeof ApiTwillotHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tweet-video': {
      id: '/api/tweet-video'
      path: '/api/tweet-video'
      fullPath: '/api/tweet-video'
      preLoaderRoute: typeof ApiTweetVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tweet-translation': {
      id: '/api/tweet-translation'
      path: '/api/tweet-translation'
      fullPath: '/api/tweet-translation'
      preLoaderRoute: typeof ApiTweetTranslationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tweet-scores': {
      id: '/api/tweet-scores'
      path: '/api/tweet-scores'
      fullPath: '/api/tweet-scores'
      preLoaderRoute: typeof ApiTweetScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tweet-expand': {
      id: '/api/tweet-expand'
      path: '/api/tweet-expand'
      fullPath: '/api/tweet-expand'
      preLoaderRoute: typeof ApiTweetExpandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/special-follow-position': {
      id: '/api/special-follow-position'
      path: '/api/special-follow-position'
      fullPath: '/api/special-follow-position'
      preLoaderRoute: typeof ApiSpecialFollowPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/special-follow-feed': {
      id: '/api/special-follow-feed'
      path: '/api/special-follow-feed'
      fullPath: '/api/special-follow-feed'
      preLoaderRoute: typeof ApiSpecialFollowFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search-discussion': {
      id: '/api/search-discussion'
      path: '/api/search-discussion'
      fullPath: '/api/search-discussion'
      preLoaderRoute: typeof ApiSearchDiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-priority': {
      id: '/api/profile-priority'
      path: '/api/profile-priority'
      fullPath: '/api/profile-priority'
      preLoaderRoute: typeof ApiProfilePriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-hydrate': {
      id: '/api/profile-hydrate'
      path: '/api/profile-hydrate'
      fullPath: '/api/profile-hydrate'
      preLoaderRoute: typeof ApiProfileHydrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-analysis': {
      id: '/api/profile-analysis'
      path: '/api/profile-analysis'
      fullPath: '/api/profile-analysis'
      preLoaderRoute: typeof ApiProfileAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/period-digest-history': {
      id: '/api/period-digest-history'
      path: '/api/period-digest-history'
      fullPath: '/api/period-digest-history'
      preLoaderRoute: typeof ApiPeriodDigestHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/period-digest': {
      id: '/api/period-digest'
      path: '/api/period-digest'
      fullPath: '/api/period-digest'
      preLoaderRoute: typeof ApiPeriodDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/network-map': {
      id: '/api/network-map'
      path: '/api/network-map'
      fullPath: '/api/network-map'
      preLoaderRoute: typeof ApiNetworkMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link-preview': {
      id: '/api/link-preview'
      path: '/api/link-preview'
      fullPath: '/api/link-preview'
      preLoaderRoute: typeof ApiLinkPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link-insights': {
      id: '/api/link-insights'
      path: '/api/link-insights'
      fullPath: '/api/link-insights'
      preLoaderRoute: typeof ApiLinkInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed-sync': {
      id: '/api/feed-sync'
      path: '/api/feed-sync'
      fullPath: '/api/feed-sync'
      preLoaderRoute: typeof ApiFeedSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed-article': {
      id: '/api/feed-article'
      path: '/api/feed-article'
      fullPath: '/api/feed-article'
      preLoaderRoute: typeof ApiFeedArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discussion-history': {
      id: '/api/discussion-history'
      path: '/api/discussion-history'
      fullPath: '/api/discussion-history'
      preLoaderRoute: typeof ApiDiscussionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data-sources': {
      id: '/api/data-sources'
      path: '/api/data-sources'
      fullPath: '/api/data-sources'
      preLoaderRoute: typeof ApiDataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation': {
      id: '/api/conversation'
      path: '/api/conversation'
      fullPath: '/api/conversation'
      preLoaderRoute: typeof ApiConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmark': {
      id: '/api/bookmark'
      path: '/api/bookmark'
      fullPath: '/api/bookmark'
      preLoaderRoute: typeof ApiBookmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blocks': {
      id: '/api/blocks'
      path: '/api/blocks'
      fullPath: '/api/blocks'
      preLoaderRoute: typeof ApiBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/action': {
      id: '/api/action'
      path: '/api/action'
      fullPath: '/api/action'
      preLoaderRoute: typeof ApiActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/xremark': {
      id: '/api/integrations/xremark'
      path: '/api/integrations/xremark'
      fullPath: '/api/integrations/xremark'
      preLoaderRoute: typeof ApiIntegrationsXremarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/twitter6551': {
      id: '/api/integrations/twitter6551'
      path: '/api/integrations/twitter6551'
      fullPath: '/api/integrations/twitter6551'
      preLoaderRoute: typeof ApiIntegrationsTwitter6551RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/twillot-history': {
      id: '/api/integrations/twillot-history'
      path: '/api/integrations/twillot-history'
      fullPath: '/api/integrations/twillot-history'
      preLoaderRoute: typeof ApiIntegrationsTwillotHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/xremark/snapshot': {
      id: '/api/integrations/xremark/snapshot'
      path: '/snapshot'
      fullPath: '/api/integrations/xremark/snapshot'
      preLoaderRoute: typeof ApiIntegrationsXremarkSnapshotRouteImport
      parentRoute: typeof ApiIntegrationsXremarkRoute
    }
    '/api/integrations/xremark/changes': {
      id: '/api/integrations/xremark/changes'
      path: '/changes'
      fullPath: '/api/integrations/xremark/changes'
      preLoaderRoute: typeof ApiIntegrationsXremarkChangesRouteImport
      parentRoute: typeof ApiIntegrationsXremarkRoute
    }
  }
}

interface ApiIntegrationsXremarkRouteChildren {
  ApiIntegrationsXremarkChangesRoute: typeof ApiIntegrationsXremarkChangesRoute
  ApiIntegrationsXremarkSnapshotRoute: typeof ApiIntegrationsXremarkSnapshotRoute
}

const ApiIntegrationsXremarkRouteChildren: ApiIntegrationsXremarkRouteChildren =
  {
    ApiIntegrationsXremarkChangesRoute: ApiIntegrationsXremarkChangesRoute,
    ApiIntegrationsXremarkSnapshotRoute: ApiIntegrationsXremarkSnapshotRoute,
  }

const ApiIntegrationsXremarkRouteWithChildren =
  ApiIntegrationsXremarkRoute._addFileChildren(
    ApiIntegrationsXremarkRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksRoute: BlocksRoute,
  BookmarksRoute: BookmarksRoute,
  DataSourcesRoute: DataSourcesRoute,
  DiscussRoute: DiscussRoute,
  DmsRoute: DmsRoute,
  FeedRoute: FeedRoute,
  InboxRoute: InboxRoute,
  LikesRoute: LikesRoute,
  LinksRoute: LinksRoute,
  MentionsRoute: MentionsRoute,
  NetworkMapRoute: NetworkMapRoute,
  ProfileAnalyzeRoute: ProfileAnalyzeRoute,
  RateLimitsRoute: RateLimitsRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRoute,
  ApiActionRoute: ApiActionRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiBlocksRoute: ApiBlocksRoute,
  ApiBookmarkRoute: ApiBookmarkRoute,
  ApiConversationRoute: ApiConversationRoute,
  ApiDataSourcesRoute: ApiDataSourcesRoute,
  ApiDiscussionHistoryRoute: ApiDiscussionHistoryRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiFeedArticleRoute: ApiFeedArticleRoute,
  ApiFeedSyncRoute: ApiFeedSyncRoute,
  ApiInboxRoute: ApiInboxRoute,
  ApiLinkInsightsRoute: ApiLinkInsightsRoute,
  ApiLinkPreviewRoute: ApiLinkPreviewRoute,
  ApiNetworkMapRoute: ApiNetworkMapRoute,
  ApiPeriodDigestRoute: ApiPeriodDigestRoute,
  ApiPeriodDigestHistoryRoute: ApiPeriodDigestHistoryRoute,
  ApiProfileAnalysisRoute: ApiProfileAnalysisRoute,
  ApiProfileHydrateRoute: ApiProfileHydrateRoute,
  ApiProfilePriorityRoute: ApiProfilePriorityRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApiSearchDiscussionRoute: ApiSearchDiscussionRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiSpecialFollowFeedRoute: ApiSpecialFollowFeedRoute,
  ApiSpecialFollowPositionRoute: ApiSpecialFollowPositionRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiTweetExpandRoute: ApiTweetExpandRoute,
  ApiTweetScoresRoute: ApiTweetScoresRoute,
  ApiTweetTranslationRoute: ApiTweetTranslationRoute,
  ApiTweetVideoRoute: ApiTweetVideoRoute,
  ApiTwillotHistoryRoute: ApiTwillotHistoryRoute,
  ApiWeeklyDigestHistoryRoute: ApiWeeklyDigestHistoryRoute,
  ApiXremarkRoute: ApiXremarkRoute,
  ApiXurlRateLimitsRoute: ApiXurlRateLimitsRoute,
  AuthorsHandleRoute: AuthorsHandleRoute,
  ProfilesHandleRoute: ProfilesHandleRoute,
  ApiIntegrationsTwillotHistoryRoute: ApiIntegrationsTwillotHistoryRoute,
  ApiIntegrationsTwitter6551Route: ApiIntegrationsTwitter6551Route,
  ApiIntegrationsXremarkRoute: ApiIntegrationsXremarkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
